version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'yat'
      MONGO_INITDB_ROOT_PASSWORD: 'yat'
      MONGO_INITDB_DATABASE: 'admin'
    networks:
      - network_example
  
  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'yat'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'yat'
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example
    depends_on: 
      - mongodb-example

networks:
  network_example:
    name: network_example
    driver: bridge