version: "3.8"

services:
  mongodb1:
    container_name: mongodb1
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./data-mongo1:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'yat'
      MONGO_INITDB_ROOT_PASSWORD: 'yat'
      MONGO_INITDB_DATABASE: 'admin'
  mongodb2:
    container_name: mongodb2
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: "./data-mongo2/"
        target: "/data/db"
        read_only: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'yat'
      MONGO_INITDB_ROOT_PASSWORD: 'yat'
      MONGO_INITDB_DATABASE: 'admin'